# Generated by Django 2.2.16 on 2022-10-25 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercode',
            name='confirmation_code',
            field=models.CharField(max_length=10),
        ),
    ]
